### ISSUE TITLE
Error Refreshing Library

### ISSUE THREAD

**Issue by KimtaJi** [openaudible/openaudible_docker#10]
![image](https://user-images.githubusercontent.com/114452570/192405696-d7373994-18dd-4b55-ac64-138db991522f.png)
Description of problem
I'm getting an "Error refreshing library." I've logged in and out like it wants me to, but I'm also getting another error with the app elsewhere with my books.json file. I store the books on an external drive as I have over 1k. It's not seeing some books that were added to my account despite trying a full and quick sync. Not a biggie, just thought I'd report it.

Json Error at launch: 
![image](https://user-images.githubusercontent.com/114452570/192405773-89f8959a-31f9-47ca-8743-320763c12881.png)

**Comment by openaudible** [comment]
Hmm. A books.json file can get damanged in earlier versions of OpenAudible if you click cancel while loading the library. That was a bug that has been fixed. Sorry for the trouble. Remove container and restart should resolve it with the latest version 3.7.5 or higher.
