### ISSUE TITLE
Old glibc version

### ISSUE THREAD

**Issue by suicidaleggroll** [openaudible/openaudible_docker#14]
Trying to download and convert a book is throwing an error:
```
SEVERE: probe error on /config/OpenAudible/aax/book.AAX size=864589812 cmd:/usr/local/OpenAudible/bin/linux_x86_64/ffprobe -hide_banner "/config/OpenAudible/aax/book.AAX" -show_streams -show_chapters -show_error -export_all 1 -show_format -print_format json 
error code:1(1)+
stdout:
stderr:/usr/local/OpenAudible/bin/linux_x86_64/ffprobe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/OpenAudible/bin/linux_x86_64/ffprobe)
/usr/local/OpenAudible/bin/linux_x86_64/ffprobe: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/OpenAudible/bin/linux_x86_64/ffprobe)
```

It appears this image is using an old Ubuntu 18.04 base with glibc 2.27.  Any suggestions for how to make ffprobe happy?

**Comment by openaudible** [comment]
We compile our own ffmpeg and ffprobe using older systems so they work on more distros. 

What version of Linux are you using? (ISO download link?) 



You could try replacing the ffmpeg and ffprobe, but we do modify the ffmpeg to support additional tags. 

You could try building from: 

https://github.com/openaudible/ffmpeg-build

And let us know what changes we could make. 

Linux c development is not our strongest suit-- so feel free to recommend a way to build a more compatible executable.

**Comment by suicidaleggroll** [comment]
I'm using the docker image here, openaudible/openaudible:latest.  It appears to be based on Ubuntu 18.04.  I haven't made any changes to the container, just trying to run it as-is

**Comment by openaudible** [comment]
Oh. We did recently push a new docker build. Will try to reproduce. What version of OpenAudible is installed? You could try rebuilding the docker container in case an old copy of OpenAudible is installed-- see the upgrade docs. 

Will try to review within 24 hours.

**Comment by suicidaleggroll** [comment]
It's running OpenAudible 4.4.6

I tried a clean pull just now:
```
docker run -d --rm -it -p 9999:3000 -e PGID=`id -g` -e PUID=`id -u` --name openaudible-test openaudible/openaudible:latest
```

Then connect to localhost:9999, open a terminal, and run:
`/usr/local/OpenAudible/bin/linux_x86_64/ffprobe` and it throws the same GLIBC_2.28 and GLIBC_2.29 error that I was seeing in the OpenAudible logs

**Comment by openaudible** [comment]
Confirmed. Had to recompile ffmpeg and probe with bionic. Will update soonish. A beta of the OpenAudible is https://openaudible.org/beta 

Thanks for the report !

**Comment by openaudible** [comment]
Reinstalling the docker container should fix this-4.4.7 was recompiled for an earlier glibc 2.27. 

Also pushed a new version here and to docker hub. 


Thank you for the report!

**Comment by suicidaleggroll** [comment]
Confirmed, I pulled the updated container and it auto-processed all outstanding books without issue.  Thanks!

**Comment by openaudible** [comment]
Revamped the docker to use the latest base image.
