### ISSUE TITLE
unable to login to account, outdated version in container

### ISSUE THREAD

**Issue by MDHMatt** [openaudible/openaudible_docker#2]
tried multiple times, reset container ect. unable to login to account to sync books.
Keeps asking for captcha challenges and when it does ask for mobile authentication it fails.

also outdated version present in container

**Comment by Weldawadyathink** [comment]
To fix the outdated container version, use the instructions for compiling from source. They do not have an auto build system in place yet, so the docker image on docker hub does not update with new versions. 

For the login issue, can you try using the windows or Mac apps? Are you able to login in those apps?

**Comment by openaudible** [comment]
Oh, shoot. Updated the docker OA to 3.3. Feel free to pull the docker again and try again.

**Comment by MDHMatt** [comment]
> 

tried to pull again and it still shows v3.2.2. removed all configs, pulled again still old version.
I tried to update via shell which did update it. possibly an error in your build script??

even after update i was struggling to login to the account

**Comment by openaudible** [comment]
Should be fixed now. Stop and remove the container.. then pull or build it again from scratch.
The first time you run it, a (GUI) terminal window should come up that does an automated install. Then it should run normally.
Version 3.4 and beyond should also fix the browser bug when logging into audible.
Fingers crossed! Feel free to report feedback.
