### ISSUE TITLE
change UID GID of files written to mounted volumes

### ISSUE THREAD

**Issue by martinjuhasz** [openaudible/openaudible_docker#4]
Is there a way to change the User ID and Group ID of the user that is writing files onto mounted volumes for config/library files?

I tried setting `PUID`, `PGID` as stated in the linuxserver/webtop documentation but without luck.

Still all files written to the config folder will result in a user with id `911`.

**Comment by openaudible** [comment]
I think so... We use webtop, so you'll have to dig into the docs: 

https://docs.linuxserver.io/general/understanding-puid-and-pgid

**Comment by martinjuhasz** [comment]
as i said, i used these env vars but it didn't have an effect.
from what i understood from the linuxserver discord, they said their images need to be used in another way that this works. but i didn't get more information

**Comment by openaudible** [comment]
I think I figured it out.. We just need to set docker environment variables -e PUID=`id -u` -e PGID=`id -g`
Feel free to pull the latest version and look at the run.sh script.

You may need to reset the owner and group of your ~/OpenAudible directory (if files were created with the wrong id)
