### ISSUE TITLE
on reboot all settings lost -- license now rejected

### ISSUE THREAD

**Issue by xxdesmus** [openaudible/openaudible_docker#9]
I just bought a license -- on reboot the docker container wiped out all my settings and when I tried to reactivate with my license -- it's rejected.

Clearly something is very broken. I just paid for a broken product it seems.

**Comment by openaudible** [comment]
Docker support is somewhat experimental.. but settings should be saved on the host machine if you used a docker volume in the run command. So you should be able to see your settings in ~/OpenAudible directory.

Here you can check your license: https://openaudible.org/license

If you have a question with the license, you can drop an email to openaudible at email dot tg with your license or email.
